export const UNIT_KERJA_OPTIONS = [
  'Semua Unit Kerja',
  'Sekretariat Itjen',
  'Inspektorat Wilayah I',
  'Inspektorat Wilayah II',
  'Inspektorat Wilayah III',
  'Inspektorat Wilayah IV',
  'Inspektorat Khusus',
]

/**
 * Daftar ruangan resmi Gedung Itjen Kemendagri
 * Sumber: Daftar Aset Barang BMN Itjen (SIMAN/DJKN), kolom "Lokasi Ruang"
 * Total: 77 ruangan resmi + opsi khusus kendaraan + belum berlokasi
 */
export const RUANGAN_GEDUNG_ITJEN = [
  // === LANTAI 1 ===
  'L01.01.01 - UNIT LAYANAN ADMINISTRASI',
  'L01.01.03 - RUANG TUNGGU/TAMU',
  'L01.01.05 - RUANG KONSULTASI',
  'L01.01.06 - COMMAND CENTER',
  'L01.01.07 - RUANG RAPAT KECIL LANTAI 1',
  'L01.01.08 - RUANG SERVER',
  'L01.01.09 - LOBBY TENGAH LT.1',
  'L01.01.10 - RUANG KERJA STAF SUBAG UMUM & KEUANGAN',
  'L01.01.11 - RUANG KEPALA BAGIAN UMUM & KEUANGAN',
  'L01.01.12 - RUANG KASUBAG UMUM',
  'L01.01.13 - RUANG KASUBAG KEUANGAN',
  'L01.01.15 - RUANG CONTROL LISTRIK',
  '01.01 - MESJID LT 1',
  '01 - GUDANG BMN',
  '01 - POS JAGA PINTU MASUK ITJEN',
  // === LANTAI 2 ===
  'L01.02.01 - RUANG ISTIRAHAT IRJEN',
  'L01.02.03 - RUANG KERJA & TAMU IRJEN',
  'L01.02.04 - RUANG RAPAT IRJEN',
  'L01.02.05 - DAPUR IRJEN',
  'L01.02.06 - RUANG KERJA TATA USAHA & RUANG TRANSIT TAMU IRJEN',
  'L01.02.07 - RUANG TENAGA AHLI IRJEN',
  'L01.02.12 - RUANG KERJA TATA USAHA & RUANG TUNGGU TAMU SEKRETARIS',
  'L01.02.13 - RUANG RAPAT SEKRETARIS',
  'L01.02.14 - RUANG KERJA SEKRETARIS',
  'L01.02.17 - LOBBY LT.2',
  // === LANTAI 3 ===
  'L01.03.01 - RUANG KERJA INSPEKTUR WILAYAH 3',
  'L01.03.04 - RUANG KERJA STAF INSPEKTORAT WILAYAH 3',
  'L01.03.05 - RUANG RAPAT  INSPEKTORAT WILAYAH 3',
  'L01.03.11 - RUANG KEPALA BAGIAN FASILITASI & ADMINISTRASI JABATAN FUNGSIONAL PPUPD',
  'L01.03.12 - RUANG KERJA STAF BAGIAN FASILITASI & ADMINISTRASI JABATAN FUNGSIONAL PPUPD',
  'L01.03.13 - RUANG KEPALA SUB BAGIAN ADMINISTRASI JABATAN FUNGSIONAL PPUPD',
  'L01.03.14 - RUANG KEPALA SUB BAGIAN FASILITASI JABATAN FUNGSIONAL PPUPD',
  'L01.03.15 - RUANG RAPAT BAGIAN FASILITASI & ADMINISTRASI JABATAN FUNGSIONAL PPUPD',
  'L01.03.16 - LOBBY LT.3',
  // === LANTAI 4 ===
  'L01.04.01 - RUANG KERJA INSPEKTUR WILAYAH 1',
  'L01.04.04 - RUANG KERJA STAF INSPEKTORAT WILAYAH 1',
  'L01.04.05 - RUANG RAPAT  INSPEKTORAT WILAYAH 1',
  'L01.04.11 - RUANG KERJA STAF UMUM & KEUANGAN',
  'L01.04.12 - RUANG ARSIP',
  'L01.04.13 - RUANG GUDANG ATK & BMN',
  'L01.04.14 - RUANG RAPAT UMUM & KEUANGAN',
  'L01.04.15 - LOBBY LT.4',
  // === LANTAI 5 ===
  'L01.05.01 - RUANG KERJA INSPEKTUR WILAYAH 2',
  'L01.05.04 - RUANG KERJA STAF INSPEKTORAT WILAYAH 2',
  'L01.05.05 - RUANG RAPAT  INSPEKTORAT WILAYAH 2',
  'L01.05.07 - DAPUR LANTAI 5',
  'L01.05.10 - RUANG KERJA KEPALA BAGIAN PERENCANAAN',
  'L01.05.11 - RUANG KERJA STAF BAGIAN PERENCANAAN',
  'L01.05.12 - RUANG KERJA KASUBBAG PENYUSUN PROGRAM DAN ANGGARAN',
  'L01.05.13 - RUANG RAPAT PERENCANAAN',
  'L01.05.14 - RUANG KERJA KASUBBAG PERATURAN PERUNDANG-UNDANGAN',
  // === LANTAI 6 ===
  'L01.06.01 - RUANG KERJA STAF INSPEKTORAT KHUSUS',
  'L01.06.03 - RUANG KERJA INSPEKTUR KHUSUS',
  'L01.06.04 - RUANG PEMERIKSAAN 1 INSPEKTORAT KHUSUS',
  'L01.06.05 - RUANG PEMERIKSAAN 2 INSPEKTORAT KHUSUS',
  'L01.06.06 - RUANG PEMERIKSAAN 3 INSPEKTORAT KHUSUS',
  'L01.06.07 - RUANG RAPAT INSPEKTORAT KHUSUS',
  'L01.06.09 - DAPUR LANTAI 6',
  'L01.06.12 - RUANG KERJA WASTAMA',
  // === LANTAI 7 ===
  'L01.07.01 - RUANG KERJA INSPEKTUR WILAYAH 4',
  'L01.07.04 - RUANG KERJA STAF INSPEKTORAT WILAYAH 4',
  'L01.07.05 - RUANG RAPAT  INSPEKTORAT WILAYAH 4',
  'L01.07.07 - DAPUR LANTAI 7',
  'L01.07.10 - RUANG KERJA STAF BAGIAN ANEV',
  'L01.07.11 - RUANG RAPAT ANEV DAN EVALUASI',
  'L01.07.13 - RUANG ARSIP ANEV',
  'L01.07.14 - RUANG KERJA KEPALA BAGIAN ANEV',
  'L01.07.15 - RUANG KERJA KASUBBAG ANEV 2',
  'L01.07.16 - RUANG KERJA KASUBBAG ANEV 1',
  'L01.07.17 - LOBBY LT.7',
  // === LANTAI 8 ===
  'L01.08.01 - RUANG RAPAT BESAR',
  'L01.08.02 - GUDANG RAPAT LANTAI 8',
  'L01.08.03 - RUANG OPERATOR LANTAI 8',
  'L01.08.06 - RUANG VIP TAMU LANTAI 8',
  'L01.08.08 - RUANG RAPAT KECIL',
  'L01.08.09 - GUDANG 1',
  'L01.08.10 - LOBBY LT.8',
  // === KHUSUS KENDARAAN & LAINNYA ===
  'Pool Kendaraan Dinas Gedung B',
  'Belum berlokasi',
]

/**
 * Map Jenis BMN (dari kolom "Jenis BMN" master SIMAN) ke kategori internal sistem.
 * Digunakan saat import master BMN untuk auto-klasifikasi sifat_aset.
 */
export const JENIS_BMN_SIFAT_MAP = {
  TANAH: 'terikat_ruangan',
  'ALAT BESAR': 'terikat_ruangan',
  'ALAT ANGKUTAN BERMOTOR': 'bergerak',
  'MESIN PERALATAN NON TIK': 'terikat_ruangan',
  'MESIN PERALATAN KHUSUS TIK': 'bergerak',
  'BANGUNAN DAN GEDUNG': 'terikat_ruangan',
  'ASET TAK BERWUJUD': 'terikat_ruangan',
}

/**
 * Map Jenis BMN ke kode kategori internal sistem.
 */
export const JENIS_BMN_KATEGORI_MAP = {
  TANAH: 'KAT-BGN',
  'ALAT BESAR': 'KAT-MBL',
  'ALAT ANGKUTAN BERMOTOR': 'KAT-KND',
  'MESIN PERALATAN NON TIK': 'KAT-MBL',
  'MESIN PERALATAN KHUSUS TIK': 'KAT-TIK',
  'BANGUNAN DAN GEDUNG': 'KAT-BGN',
  'ASET TAK BERWUJUD': 'KAT-TIK',
}
